# ---- Stage 1. build the exutable JAR ----
FROM eclipse-temurin:26-jdk AS build
WORKDIR /workspace

COPY gradlew settings.gradle.kts build.gradle.kts ./
COPY gradle ./gradle
COPY src ./src

# Windows may leave CRLF line endings in the script. Normalize them for Linux.
RUN sed -i 's/\r$//' gradlew && chmod +x gradlew

# Tests are intentionally skipped here. Integration tests start MySQL container
# via Testcontainers, which cannot run inside docker build.
# Before building the image, run tests on the host - ./gradlew test.
RUN --mount=type=cache,target=/root/.gradle \
    ./gradlew --no-daemon bootJar -x test

# ---- Stage 2. lightweight runtime image ----
FROM eclipse-temurin:26-jre
WORKDIR /app

# The application should not run as root.
RUN groupadd --system app && useradd --system --gid app --no-create-home app

# The glob excludes the *-plain.jar generated by Gradle alongside the application JAR.
COPY --from=build /workspace/build/libs/*-SNAPSHOT.jar app.jar

USER app
EXPOSE 8080

ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]