CREATE TABLE accounts (
id VARCHAR(36) NOT NULL PRIMARY KEY,
account_number VARCHAR(24) NOT NULL UNIQUE,
owner_id VARCHAR(255) NOT NULL,
balance_amount DECIMAL(19, 2) NOT NULL,
currency VARCHAR(3) NOT NULL,
overdraft_limit DECIMAL(19, 2) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
id VARCHAR(36) NOT NULL PRIMARY KEY,
user_id VARCHAR(255) NOT NULL,
title VARCHAR(255) NOT NULL,
message TEXT NOT NULL,
created_at TIMESTAMP NOT NULL,
is_read BOOLEAN NOT NULL DEFAULT FALSE
);